# Generated by Django 3.1.7 on 2021-04-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='door',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='landmark',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
