# Generated by Django 3.1.7 on 2021-04-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fstnm', models.CharField(max_length=200, null=True)),
                ('lsnm', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=12, null=True)),
                ('phone', models.IntegerField(max_length=200, null=True)),
                ('books', models.IntegerField(max_length=200, null=True)),
                ('doorno', models.CharField(max_length=200, null=True)),
                ('landmark', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('pincode', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
