# Generated by Django 3.1.7 on 2021-04-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210408_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='books',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='donate',
            name='phone',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
