# Generated by Django 3.1.7 on 2021-04-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210408_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('LIKE NEW', 'LIKE NEW'), ('VERY GOOD', 'VERY GOOD'), ('GOOD', 'GOOD'), ('FAIR', 'FAIR'), ('POOR', 'POOR')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='isbn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pic',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='donate',
            name='books',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='donate',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
