# Generated by Django 3.1.7 on 2021-04-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_order_date_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(choices=[('4', 'Engineering'), ('5', 'Medical'), ('GOOD', 'GOOD'), ('FAIR', 'FAIR'), ('POOR', 'POOR')], to='accounts.Category'),
        ),
    ]
