# Generated by Django 3.1.7 on 2021-04-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210413_1047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Tag',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(choices=[('4', 'Engineering'), ('5', 'Medical'), ('GOOD', 'GOOD'), ('FAIR', 'FAIR'), ('POOR', 'POOR')], to='accounts.Tag'),
        ),
    ]
