# Generated by Django 3.1.7 on 2021-04-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210413_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(choices=[('4', 'Engineering'), ('VERY GOOD', 'Medical'), ('GOOD', 'GOOD'), ('FAIR', 'FAIR'), ('POOR', 'POOR')], to='accounts.Tag'),
        ),
    ]
