# Generated by Django 3.1.7 on 2021-04-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210413_1057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(choices=[('4', 'Engineering'), ('5', 'Medical'), ('8', 'Economics'), ('6', 'MPC Inter'), ('7', 'BiPC Inter')], to='accounts.Category'),
        ),
    ]
