# Generated by Django 3.1.7 on 2021-04-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210413_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_count',
            field=models.FloatField(null=True),
        ),
    ]
