# Generated by Django 3.1.7 on 2021-05-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20210501_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(choices=[('1', 'Engineering'), ('2', 'Medical'), ('3', 'Economics'), ('4', 'MPC Inter'), ('5', 'BiPC Inter')], to='accounts.Category'),
        ),
    ]
