# Generated by Django 3.1.7 on 2021-05-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20210501_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalorder',
            name='price2',
            field=models.FloatField(null=True),
        ),
    ]
