# Generated by Django 3.1.7 on 2021-05-01 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_finalorder_price2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinalOrder',
            new_name='FinalOrders',
        ),
    ]
