# Generated by Django 3.1.7 on 2021-05-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20210501_1550'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinalOrders',
            new_name='FinalOrder',
        ),
    ]
