# Generated by Django 3.1.7 on 2021-05-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20210501_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalorder',
            name='price2',
        ),
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
