# Generated by Django 3.1.7 on 2021-05-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20210502_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalorder',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='booksdonated',
            field=models.IntegerField(default=0),
        ),
    ]
